services:
  vyfony_filterable_table.data_collector:
    class: Vyfony\Bundle\FilterableTableBundle\DataCollector\DataCollector
    arguments:
      - '@doctrine'
      - ~
      - ~

  Vyfony\Bundle\FilterableTableBundle\DataCollector\DataCollectorInterface: '@vyfony_filterable_table.data_collector'

  vyfony_filterable_table.form.data:
    class: Vyfony\Bundle\FilterableTableBundle\Form\Data\FormData
    arguments:
      - '@request_stack'
      - '@Vyfony\Bundle\FilterableTableBundle\Form\Transformer\QueryParametersTransformerInterface'

  Vyfony\Bundle\FilterableTableBundle\Form\Data\FormDataInterface: '@vyfony_filterable_table.form.data'

  vyfony_filterable_table.table:
    class: Vyfony\Bundle\FilterableTableBundle\Table\Table
    arguments:
      - '@Vyfony\Bundle\FilterableTableBundle\DataCollector\DataCollectorInterface'
      - '@form.factory'
      - '@Vyfony\Bundle\FilterableTableBundle\Form\Data\FormDataInterface'
      - ~
      - ~
      - ~

  Vyfony\Bundle\FilterableTableBundle\Table\TableInterface: '@vyfony_filterable_table.table'

  vyfony_filterable_table.table_interface: '@Vyfony\Bundle\FilterableTableBundle\Table\TableInterface'

  vyfony_filterable_table.form.transformer.query_parameters_transformer:
    class: Vyfony\Bundle\FilterableTableBundle\Form\Transformer\QueryParametersTransformer

  Vyfony\Bundle\FilterableTableBundle\Form\Transformer\QueryParametersTransformerInterface: '@vyfony_filterable_table.form.transformer.query_parameters_transformer'

  vyfony_filterable_table.form.type.filterable_table_type:
    class: Vyfony\Bundle\FilterableTableBundle\Form\Type\FilterableTableType
    arguments:
      - ~
      - ~
    tags: ['form.type']